services:
    app:
        build:
            context: .
            args:
                - DATABASE_TYPE=${DATABASE_TYPE:-sqlite}
                - USE_MIRROR=${USE_MIRROR:-true}
        image: dataset-loom:latest
        init: true
        ports:
            - '${HOST_PORT:-2088}:${CONTAINER_PORT:-2088}'
        environment:
            - NODE_ENV=production
            - DATABASE_URL=file:/data/db.sqlite
        volumes:
            - sqlite_data:/data
            - ./local-db:/app/data/local-db
        restart: unless-stopped

volumes:
    sqlite_data:
