services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3088:3088"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/datasetloom.sqlite
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3088/api" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - qdrant

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "2088:2088"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    depends_on:
      - api
  qdrant:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
